### PR TITLE
Serialization to TOML

### PR DESCRIPTION
**Pull request by dilecti**
Adding support for generating TOML from objects and Toml instances.

### CODE REVIEW

**Comment by mwanji** [comment]
Thanks a lot for this! I haven't had time yet to look at this in-depth, but I'm going to list some things I'd like to change. You can make the changes or I'll make them when I can.

* Serialise to File, OutputStream and Writer. These mirror the parse methods. These can all delegate to serialize(Writer).
* Is it necessary to serialize a Toml instance? As Toml is immutable, the result will always be the same as the original input.
* Could the existing ValueConverter implementations handle serialisation as well? It's easier to have both conversions in the same place, I think.
* In DateSerializer, SimpleDateFormat is not thread-safe, so should be a final static field.
* Test names should be in the should_x_y_z format. See other tests for examples.
* Re-use encoder tests from https://github.com/BurntSushi/toml-test if possible
* I don't really like the pairing of parse / serialize. They both feel too technical. Maybe we can keep it basic: read / write ? parse -> read is a breaking change, but serialize -> write has no impact.
* Should write be a static method on Toml? Perhaps a TomlWriter class with an instance method? This would allow a similar configuration system with defaults and settings, such as indentation depth, optionally listing empty tables, etc. Configured instances could then be passed around, eg. via dependency injection.

**Comment by dilecti** [comment]
Thanks for the feedback! I'll make a couple of the quick changes now, then work on more when I have time later.

Serializing a Toml instance: good point there, we don't need it. I would like a way to test that parsing and then serializing yields the same result, so would you be open to a package-private method to retrieve the Toml's values?

Folding Serialization into ValueConverters: I couldn't find much opportunity for code sharing between parsers and serializers, and liked the more granular separation of responsibilities when split. But I don't feel strongly about it, and would be happy to fold them together if you do feel strongly :)

parse / serialize: I considered parse / render, but `Renderer` seems awkward. serialize -> write sounds better.

Toml.write vs Toml.Writer: I need to ponder this some more.

**Comment by mwanji** [comment]
> I would like a way to test that parsing and then serializing yields the same result, so would you be open to a package-private method to retrieve the Toml's values?

If you read, then write, can't you just compare the output to the original input?

> Folding Serialization into ValueConverters

I see it as "here's where booleans are handled; here's where strings are handled". There might be separate ValueReader and ValueWriter interfaces, for example, but BooleanConverter would implement both.

**Comment by dilecti** [comment]
I've made a bunch of changes based on your feedback:

-  Serialise to File, OutputStream and Writer.
-  Serialize -> write. I didn't change parse to read, since (as you noted) that would be a breaking change, and I'd be more comfortable if you did it.
-  Moved the static writing methods out of Toml, and created a TomlWriter class.
-  Added a number of options for controlling output format to TomlWriter.
-  Added encoder functionality to BurntSushiValidTest, and used a number of the tests there to test encoding. A number of them are not applicable, as they exercise things like whitespace variations that are more interesting to decoders.

Speaking of the BurntSushi/toml-tests, do you have an automated way to run those? Or do you run them by hand? Or do you just copy them into toml4j and use its test harness?

**Comment by mwanji** [comment]
That's great, I really appreciate it. I'll work on it this week to get it
merged.

> Speaking of the BurntSushi/toml-tests, do you have an automated way to
run those? Or do you run them by hand? Or do you just copy them into toml4j
and use its test harness?

I have a project that runs toml-test automatically, but haven't made it
public or integrated it into toml4j. The main problem is that the
BurntSushi project has fallen way out of date and doesn't seem to be
getting any attention. Lots of functionality is untested and several tests
are wrong due to language changes.

**Comment by mwanji** [comment]
I merged this into a new branch called writer and made you a collaborator. I've made a few changes and will continue working on it on that branch until it's ready.

**Comment by mwanji** [comment]
Here are a few more issues. Don't feel obliged to do them all, I'll get to them as soon as I can.

- It would be better if TomlWriter#write(Object, OutputStream) wrote directly to the stream, rather than buffering the string in memory. This could be achieved by passing a Writer to WRITERS#write and using it instead of a StringBuilder. Then, all the other write methods become syntactic sugar for TomlWriter#write(Object, Writer).
- All write methods should have an example in the readme.
- Get rid of raw type warnings
- TomlWriter should be immutable. Maybe TomlWriter.Builder ?
- Should TomlWriter have Toml write(Object) ?

**Comment by mwanji** [comment]
I think the date methods on TomlWriter should be removed. TOML only supports one date format, within which to only variation is how the timezone is written. Is there another reason for them to be there?

**Comment by dilecti** [comment]
The date methods exist only to control the formatting of the local offset. I do think we need to preserve that capability, but I can only think of suboptimal ways to do so:

1.  Allow the caller to pass in an object that takes a `Date` and returns a `String` containing the local offset representation.
2.  Allow the caller to pass in a `SimpleDateFormat` local offset format string.
3.  Allow the caller to pass in a `DateFormat` to format the entire datetime (as the code currently does).
4.  Provide our own enum that enumerates the set of possible valid TOML local offset formats, and provide a method that allows callers to pass this enum value to choose the local offset format.

#1-3 do not prevent callers from generating invalid TOML.

#2 also suffers from the fact that Java 6 does not support `XXX`, which I expect will be a common choice.

As I write this#4 seems like the strongest solution. The only thing I don't like about it is that it smells a bit of reinventing wheels.

**Comment by dilecti** [comment]
-  _TomlWriter should be immutable. Maybe TomlWriter.Builder?_  I agree that a TomlWriter.Builder is the way to go to make TomlWriter immutable.

-  _Should TomlWriter have Toml write(Object) ?_  An interesting idea. What do you think the use cases are?

-  _Does the indentation policy need its own class?_  When I started writing the indentation policy controls, I thought there would be more than two (in which case I think it helps callers by collecting them all in one place). But since we ended up with just two, I don't think there is a strong case for preserving an independent policy class.

-  _Are the ValueWriter#toString() methods necessary? The default toString() will show the object's class._  The results of toString() appear in the message of the IllegalStateException thrown if a heterogeneous array is found. The intent is to help the caller to find the offending type. I was thinking that a more human-friendly type name would be preferable to a stringified class name (of the Writer) in that message. A possible better alternative might be to use the stringified class name of the object found.

**Comment by mwanji** [comment]
> As I write this#4 seems like the strongest solution. The only thing I don't like about it is that it smells a bit of reinventing wheels.

We could also start by writing the date in the UTC timezone by default. Afterwards, a timezone option could be added to TomlWriter.Builder (which already exists on writer branch).

I believe only one option is necessary, as in TOML either it's UTC or an hour offset. If a TimeZone is specified, the hour offset must be used. So calling Builder#timeZone(TimeZone) necessarily implies the hour offset format. As for implementation, on Java 7+ we could use the X format. On Java 6, we can use Z and modify the output to add a colon.

**Comment by mwanji** [comment]
I just noticed this: 

`final int aFinalInt = 1; // Should be skipped`

Why are final fields skipped?

**Comment by dilecti** [comment]
Regarding local offset representation: You are right, we only need one option. I certainly overcomplicated that!

**Comment by dilecti** [comment]
Skipping final fields: A common pattern in configuration objects is to use `private static final` fields to hold constants. For this pattern, I don't think we want to write those to TOML. And if they were written to TOML, it wouldn't be right to parse them back into POJOs (if the parser even permitted that).

A second (perhaps not so great) reason is that classes defined inline in methods have an auto-generated final field referencing the enclosing scope, and it doesn't make sense to write them out.

Do you think there are use cases for writing final fields? If so, should we make it an option?

**Comment by mwanji** [comment]
> Skipping final fields: A common pattern in configuration objects is to use private static final fields to hold constants. For this pattern, I don't think we want to write those to TOML. And if they were written to TOML, it wouldn't be right to parse them back into POJOs (if the parser even permitted that).

I agree with this. However, the field in question isn't static. Non-static final fields might have been set via a constructor and should be written to TOML.

> A second (perhaps not so great) reason is that classes defined inline in methods have an auto-generated final field referencing the enclosing scope, and it doesn't make sense to write them out.

I'd never used local classes before, so didn't know about that. It might be possible to work around this by skipping synthetic fields.

**Comment by mwanji** [comment]
I just noticed that writing objects that have ValueWriters (eg. Date, String, etc) produces incorrect TOML:

```java
new TomlWriter().write("1") // => "1"
new TomlWriter().write(new Date()) // => 2015-07-02T06:26:16Z
```
Top-level input should probably be restricted to maps and custom objects.

**Comment by dilecti** [comment]
Writing objects that have ValueWriters: I am of two minds on this one. The case for permitting a TomlWriter to generate TOML fragments is versatility: a caller can use it to get, for example, a TOML-escaped String.

I can also see the value of strictly enforcing correct TOML output (and almost added it, but ultimately deferred the decision).

**Comment by dilecti** [comment]
On thread safety: while multiple threads can use the same TomlWriter instance concurrently, bad things will happen if they both use the same OutputStream or Writer. There is no good way to serialize operations in this case. Probably obvious, but worth mentioning in the readme?

**Comment by mwanji** [comment]
> Writing objects that have ValueWriters: I am of two minds on this one. The case for permitting a TomlWriter to generate TOML fragments is versatility: a caller can use it to get, for example, a TOML-escaped String.

That's a good point. In this case, I would argue that it is better to be restrictive early on. We can safely add this feature later on, whereas we cannot safely remove it if it becomes problematic in the future. An alternative would be to add methods such as write(Date) that emit partial TOML. Is there much of a usecase for this? I've never had the need to emit partial JSON, for example.

**Comment by dilecti** [comment]
_Writing TOML fragments_: Regarding use cases, I could envision a developer wondering how something might be encoded, and slightly fewer lines of explorative code is always nice. For JSON, it's easy to explore via one of the many online web sites that let you play around with JSON. But it's certainly not a mainstream use case, and your point of not being able to change the interface later is well taken. I will push a change to prevent emitting fragments.

**Comment by mwanji** [comment]
Is it necessary to Unicode escape characters such as € and é? I see this in TomlWriterTest#should_write_strings_to_toml_utf8(). It feels like it would be nicer to emit the literals. Especially if the file contains i18n strings in a language other than English, for example.

**Comment by dilecti** [comment]
It is not necessary to escape those characters; the code is a bit simplistic about its approach at this point. Is there a better way to tell what should and shouldn't be escaped?

**Comment by mwanji** [comment]
Since we're starting with Java strings, I'm not sure we can tell what was originally escaped and what wasn't. I think it's much easier to read the unescaped symbols. We can continue to escape TOML's special characters (except newline, as per #21 ), but unless there are hidden gotchas, I think Unicode should not be escaped.

**Comment by mwanji** [comment]
`specialCharacterEscapes[0x0C] = "\\f";`

Is there a special reason to use hex here? Don't get me wrong, it looks badass, but I fear it might lead to confusion in the future. All the tests pass with decimal numbers, too. Unless the hex indicates that you're doing character code point manipulations? maybe named static variables, or at least a comment, could clarify?

**Comment by dilecti** [comment]
I agree that unescaped symbols are easier to read. I'm not sure how to do it, though - Java Strings are 16-bit code points, which we need to convert to UTF-8 (per the TOML spec). You can convert to UTF-8-encoded byte-arrays, but then what do you do?

**Comment by dilecti** [comment]
There is no particular reason to use hex for the specialCharacterEscapes; it felt natural to me (probably from too much time spent with `man ascii` in past projects).

**Comment by dilecti** [comment]
I changed the special character escapes to use characters (e.g. `'\t'`). Do you like this better?

**Comment by dilecti** [comment]
If my reading of Wikipedia et al. is correct, we need to escape Unicode characters such as € to produce UTF-8 encoded text.

**Comment by mwanji** [comment]
> I changed the special character escapes to use characters (e.g. '\t'). Do you like this better?

That's a great idea, thanks.

> If my reading of Wikipedia et al. is correct, we need to escape Unicode characters such as € to produce UTF-8 encoded text.

Here's [how to write Java Strings to UTF-8](https://docs.oracle.com/javase/tutorial/i18n/text/string.html).

I'm wondering if it's better to do this in the StringConverter or configure it in the underlying Writer somehow. The thing is that we have to handle strings character by character, but doing the UTF-8 encoding per character seems like it would create a lot of work.

**Comment by dilecti** [comment]
I'm looking at the changes you made to avoid escaping Unicode characters, and I'm not sure the resulting code is correct, in that it is not guaranteed to output UTF-8.

The encoding used by the caller-provided writer can be any encoding; it can either be set by the library user on the Writer provided, or if not set, if will be the whatever the JVM default encoder is (which happens to be UTF-8 on my platform). So if the encoder is set to anything other than UTF-8, we may not be generating valid TOML.

The efficiency issue you raise is tricky. I don't see any way to override the encoder on a Writer instance. The removed code only had to do additional work if the code point was outside the ASCII range, which seems fairly efficient (at least for users who use predominantly ASCII characters).

**Comment by mwanji** [comment]
> The encoding used by the caller-provided writer can be any encoding; it can either be set by the library user on the Writer provided, or if not set, if will be the whatever the JVM default encoder is (which happens to be UTF-8 on my platform). So if the encoder is set to anything other than UTF-8, we may not be generating valid TOML.

Good point. I'll add this to the javadoc for write(Object, OutputStream) and write(Object, Writer) and change write(Object, File) to set the encoding to UTF-8.

> I'm looking at the changes you made to avoid escaping Unicode characters, and I'm not sure the resulting code is correct, in that it is not guaranteed to output UTF-8.

You may be right. I haven't had time to dig into the article I linked to earlier and implement it, but I'll try to get to that, or maybe restore your previous implementation. Do you know how we could test that the output really is UTF-8?

**Comment by mwanji** [comment]
I've merged this into wip, so the remaining small fixes can be done there.

Any ideas for testing UTF-8 output?

**Comment by dilecti** [comment]
Sorry for the tardy response. Regarding testing UTF-8 output: is this just for writing some unit tests?

I was hoping the core libraries would be able to help here, but they don't seem to check for valid UTF-8. For example, here are some invalid UTF-8 bytes which Java accepts when constructing a String:

```
        byte[] bytes = {(byte) 0xC0, 0x50 };
        String string = new String(bytes, StandardCharsets.UTF_8);
        System.out.println(string);
```

**Pull request merged**
