### PR TITLE
Default values

### PR DESCRIPTION
**Pull request by udiabon**
Add methods with new parameter "default value", if the key was not found the "default value" will be returned, this could make the coding job more comfortable and more effective.

### CODE REVIEW

**Comment by mwanji** [comment]
Thanks a lot for this, I'd been thinking about adding something similar.

Have you tried to use the existing defaults system? Was it not sufficient/useful/obvious/etc. enough? Do you think both should co-exist (java.util.Properties has both, so that's a strong argument in favour of having both)?

In your implementation, constructor-level defaults override method-level defaults. I think this makes sense. Do you agree? If so, please add some tests for this case.

Also, I've been thinking of adding Java 8 functionality that returns Optional, eg. `Optional<String> getStringOptional(String)`. That would make it easier to integrate into lambda/stream operations. In this scenario, there would also be a java 6-compatible version using overloaded methods.

Could you please make the following modifications:

* change this PR to be against the wip branch? (I just realised that that is not stated in CONTRIBUTING.md and have added it)
* The overloaded methods should call the original method, eg. `getBoolean(String)` rather than `get(String)`. That will avoid duplicating the work done in the original method.
* Remove the .gitignore. I use a global .gitignore so I don't have to repeat the same exclusions in every project

**Comment by mwanji** [comment]
I just realised I can merge it into wip myself (obviously!), so never mind that.

**Comment by udiabon** [comment]
Thanks for your quick response, the code was refactored according to your advice.

> Have you tried to use the existing defaults system? Was it not sufficient/useful/obvious/etc. enough? Do you think both should co-exist (java.util.Properties has both, so that's a strong argument in favour of having both)?

Yes, I think so.

> In your implementation, constructor-level defaults override method-level defaults. I think this makes sense. Do you agree? If so, please add some tests for this case.

I thinks, method-level defaults should override constructor-level defaults, this is more conventional.

**Comment by mwanji** [comment]
> I thinks, method-level defaults should override constructor-level defaults, this is more conventional.

I just checked, and in java.util.Properties, constructor defaults override method defaults. This makes sense, as the properties chain is checked first, which includes the constructor defaults, and the method default is used only if the properties chain returns null. toml4j will have the same behaviour.

**Comment by mwanji** [comment]
Also, is there a reason for not having a default method for getList?

**Comment by mwanji** [comment]
I've merged your changes into the [default_values](https://github.com/mwanji/toml4j/tree/default_values) branch, added defaults for arrays and updated the readme and change log. Let me know if it looks OK to you.

**Comment by udiabon** [comment]
> I just checked, and in java.util.Properties, constructor defaults override method defaults. This makes sense, as the properties chain is checked first, which includes the constructor defaults, and the method default is used only if the properties chain returns null. toml4j will have the same behaviour.

I misunderstood what you meant, i agree your point.

BTW: I just forgot to add a default method for getList.

*I have reviewed your code of the default method for getList, there is a bug, the original getList returns an empty list if the key was not found in the properties chain, therefore, the defaultValue will never be returned.*

**Comment by mwanji** [comment]
On [this line](https://github.com/mwanji/toml4j/commit/d958baebb561b718be2df1d3de0372d43f2230b7#diff-03f26ca2c943ca83f00a8f6f47d0c981R177) I use the lower-level `get(String)`, which returns null if the key is missing. And there's a [test](https://github.com/mwanji/toml4j/commit/d958baebb561b718be2df1d3de0372d43f2230b7#diff-f8cc9403d7cdad2ab9084d9fed7db8dbR107) to verify behaviour.

Is this incorrect, for you? If so, please provide a code snippet that shows the bug.

**Comment by udiabon** [comment]
Yes you are right, i misread the code, i should read more carefully and run the test to verify behavior.

**Comment by mwanji** [comment]
This is now on the wip branch. It will be released whenever there's an upstream release, unless you need an official release before then. Otherwise, you can build from wip.

**Comment by c-rack** [comment]
@mwanji I would love to see this in an official release, too.
Do you have any plans when to release the next version?

**Comment by mwanji** [comment]
@c-rack I'd been waiting for the next toml release, but it's been way too long. I'll clean up the wip branch and release 0.5 as soon as I can.

**Comment by c-rack** [comment]
Thanks!

**Comment by mwanji** [comment]
I've released 0.5.0 to Maven Central, it should be up there soon. There are a few breaking changes, make sure to look at the changelog.

**Comment by c-rack** [comment]
That was quick, thanks! :+1:

**Pull request merged**
